{
//=========Macro generated from canvas: c1/c1
//=========  (Sat Feb  4 22:19:49 2017) by ROOT version5.34/36
   TCanvas *c1 = new TCanvas("c1", "c1",68,44,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->Range(-0.24,-0.18,1.26,1.32);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.16);
   c1->SetRightMargin(0.04);
   c1->SetTopMargin(0.08);
   c1->SetBottomMargin(0.12);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TH1F *phAxis = new TH1F("phAxis","",1,0,1.2);
   phAxis->SetMinimum(0);
   phAxis->SetMaximum(1.2);
   phAxis->SetLineStyle(0);
   phAxis->SetMarkerStyle(20);
   phAxis->GetXaxis()->SetTitle("Binding energy [GeV]");
   phAxis->GetXaxis()->CenterTitle(true);
   phAxis->GetXaxis()->SetLabelFont(42);
   phAxis->GetXaxis()->SetLabelOffset(0.007);
   phAxis->GetXaxis()->SetLabelSize(0.05);
   phAxis->GetXaxis()->SetTitleSize(0.06);
   phAxis->GetXaxis()->SetTitleOffset(0.9);
   phAxis->GetXaxis()->SetTitleFont(42);
   phAxis->GetYaxis()->SetTitle("R_{AA}");
   phAxis->GetYaxis()->CenterTitle(true);
   phAxis->GetYaxis()->SetLabelFont(42);
   phAxis->GetYaxis()->SetLabelOffset(0.007);
   phAxis->GetYaxis()->SetLabelSize(0.05);
   phAxis->GetYaxis()->SetTitleSize(0.06);
   phAxis->GetYaxis()->SetTitleOffset(1.25);
   phAxis->GetYaxis()->SetTitleFont(42);
   phAxis->GetZaxis()->SetLabelFont(42);
   phAxis->GetZaxis()->SetLabelOffset(0.007);
   phAxis->GetZaxis()->SetLabelSize(0.05);
   phAxis->GetZaxis()->SetTitleSize(0.06);
   phAxis->GetZaxis()->SetTitleFont(42);
   phAxis->Draw("");
   TLine *line = new TLine(0,1,1.2,1);
   line->Draw();
   
   TGraphErrors *gre = new TGraphErrors(1);
   gre->SetName("Graph0");
   gre->SetTitle("Graph");

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#99ff99");
   gre->SetFillColor(ci);
   gre->SetMarkerStyle(20);
   gre->SetPoint(0,1.1,0.364);
   gre->SetPointError(0,0.02,0.048);
   
   TH1F *Graph_Graph1 = new TH1F("Graph_Graph1","Graph",100,1.076,1.124);
   Graph_Graph1->SetMinimum(0.3064);
   Graph_Graph1->SetMaximum(0.4216);
   Graph_Graph1->SetDirectory(0);
   Graph_Graph1->SetStats(0);
   Graph_Graph1->SetLineStyle(0);
   Graph_Graph1->SetMarkerStyle(20);
   Graph_Graph1->GetXaxis()->SetLabelFont(42);
   Graph_Graph1->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph1->GetXaxis()->SetLabelSize(0.05);
   Graph_Graph1->GetXaxis()->SetTitleSize(0.06);
   Graph_Graph1->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph1->GetXaxis()->SetTitleFont(42);
   Graph_Graph1->GetYaxis()->SetLabelFont(42);
   Graph_Graph1->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph1->GetYaxis()->SetLabelSize(0.05);
   Graph_Graph1->GetYaxis()->SetTitleSize(0.06);
   Graph_Graph1->GetYaxis()->SetTitleOffset(1.25);
   Graph_Graph1->GetYaxis()->SetTitleFont(42);
   Graph_Graph1->GetZaxis()->SetLabelFont(42);
   Graph_Graph1->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph1->GetZaxis()->SetLabelSize(0.05);
   Graph_Graph1->GetZaxis()->SetTitleSize(0.06);
   Graph_Graph1->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph1);
   
   gre->Draw("2");
   
   gre = new TGraphErrors(1);
   gre->SetName("Graph1");
   gre->SetTitle("Graph");

   ci = TColor::GetColor("#9999ff");
   gre->SetFillColor(ci);
   gre->SetMarkerStyle(20);
   gre->SetPoint(0,0.54,0.104);
   gre->SetPointError(0,0.02,0.014);
   
   TH1F *Graph_Graph2 = new TH1F("Graph_Graph2","Graph",100,0.516,0.564);
   Graph_Graph2->SetMinimum(0.0872);
   Graph_Graph2->SetMaximum(0.1208);
   Graph_Graph2->SetDirectory(0);
   Graph_Graph2->SetStats(0);
   Graph_Graph2->SetLineStyle(0);
   Graph_Graph2->SetMarkerStyle(20);
   Graph_Graph2->GetXaxis()->SetLabelFont(42);
   Graph_Graph2->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph2->GetXaxis()->SetLabelSize(0.05);
   Graph_Graph2->GetXaxis()->SetTitleSize(0.06);
   Graph_Graph2->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph2->GetXaxis()->SetTitleFont(42);
   Graph_Graph2->GetYaxis()->SetLabelFont(42);
   Graph_Graph2->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph2->GetYaxis()->SetLabelSize(0.05);
   Graph_Graph2->GetYaxis()->SetTitleSize(0.06);
   Graph_Graph2->GetYaxis()->SetTitleOffset(1.25);
   Graph_Graph2->GetYaxis()->SetTitleFont(42);
   Graph_Graph2->GetZaxis()->SetLabelFont(42);
   Graph_Graph2->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph2->GetZaxis()->SetLabelSize(0.05);
   Graph_Graph2->GetZaxis()->SetTitleSize(0.06);
   Graph_Graph2->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph2);
   
   gre->Draw("2");
   
   gre = new TGraphErrors(1);
   gre->SetName("Graph2");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);

   ci = TColor::GetColor("#009900");
   gre->SetMarkerColor(ci);
   gre->SetMarkerStyle(29);
   gre->SetMarkerSize(1.7);
   gre->SetPoint(0,1.1,0.364);
   gre->SetPointError(0,0,0.014);
   
   TH1F *Graph_Graph3 = new TH1F("Graph_Graph3","Graph",100,1,2.2);
   Graph_Graph3->SetMinimum(0.3472);
   Graph_Graph3->SetMaximum(0.3808);
   Graph_Graph3->SetDirectory(0);
   Graph_Graph3->SetStats(0);
   Graph_Graph3->SetLineStyle(0);
   Graph_Graph3->SetMarkerStyle(20);
   Graph_Graph3->GetXaxis()->SetLabelFont(42);
   Graph_Graph3->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph3->GetXaxis()->SetLabelSize(0.05);
   Graph_Graph3->GetXaxis()->SetTitleSize(0.06);
   Graph_Graph3->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph3->GetXaxis()->SetTitleFont(42);
   Graph_Graph3->GetYaxis()->SetLabelFont(42);
   Graph_Graph3->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph3->GetYaxis()->SetLabelSize(0.05);
   Graph_Graph3->GetYaxis()->SetTitleSize(0.06);
   Graph_Graph3->GetYaxis()->SetTitleOffset(1.25);
   Graph_Graph3->GetYaxis()->SetTitleFont(42);
   Graph_Graph3->GetZaxis()->SetLabelFont(42);
   Graph_Graph3->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph3->GetZaxis()->SetLabelSize(0.05);
   Graph_Graph3->GetZaxis()->SetTitleSize(0.06);
   Graph_Graph3->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph3);
   
   gre->Draw("p");
   
   gre = new TGraphErrors(1);
   gre->SetName("Graph3");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);

   ci = TColor::GetColor("#000099");
   gre->SetMarkerColor(ci);
   gre->SetMarkerStyle(34);
   gre->SetMarkerSize(1.7);
   gre->SetPoint(0,0.54,0.104);
   gre->SetPointError(0,0,0.021);
   
   TH1F *Graph_Graph4 = new TH1F("Graph_Graph4","Graph",100,0.44,1.64);
   Graph_Graph4->SetMinimum(0.0788);
   Graph_Graph4->SetMaximum(0.1292);
   Graph_Graph4->SetDirectory(0);
   Graph_Graph4->SetStats(0);
   Graph_Graph4->SetLineStyle(0);
   Graph_Graph4->SetMarkerStyle(20);
   Graph_Graph4->GetXaxis()->SetLabelFont(42);
   Graph_Graph4->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph4->GetXaxis()->SetLabelSize(0.05);
   Graph_Graph4->GetXaxis()->SetTitleSize(0.06);
   Graph_Graph4->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph4->GetXaxis()->SetTitleFont(42);
   Graph_Graph4->GetYaxis()->SetLabelFont(42);
   Graph_Graph4->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph4->GetYaxis()->SetLabelSize(0.05);
   Graph_Graph4->GetYaxis()->SetTitleSize(0.06);
   Graph_Graph4->GetYaxis()->SetTitleOffset(1.25);
   Graph_Graph4->GetYaxis()->SetTitleFont(42);
   Graph_Graph4->GetZaxis()->SetLabelFont(42);
   Graph_Graph4->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph4->GetZaxis()->SetLabelSize(0.05);
   Graph_Graph4->GetZaxis()->SetTitleSize(0.06);
   Graph_Graph4->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph4);
   
   gre->Draw("p");
   
   gre = new TGraphErrors(1);
   gre->SetName("Graph4");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerStyle(30);
   gre->SetMarkerSize(1.7);
   gre->SetPoint(0,1.1,0.364);
   gre->SetPointError(0,0,0.014);
   
   TH1F *Graph_Graph5 = new TH1F("Graph_Graph5","Graph",100,1,2.2);
   Graph_Graph5->SetMinimum(0.3472);
   Graph_Graph5->SetMaximum(0.3808);
   Graph_Graph5->SetDirectory(0);
   Graph_Graph5->SetStats(0);
   Graph_Graph5->SetLineStyle(0);
   Graph_Graph5->SetMarkerStyle(20);
   Graph_Graph5->GetXaxis()->SetLabelFont(42);
   Graph_Graph5->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph5->GetXaxis()->SetLabelSize(0.05);
   Graph_Graph5->GetXaxis()->SetTitleSize(0.06);
   Graph_Graph5->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph5->GetXaxis()->SetTitleFont(42);
   Graph_Graph5->GetYaxis()->SetLabelFont(42);
   Graph_Graph5->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph5->GetYaxis()->SetLabelSize(0.05);
   Graph_Graph5->GetYaxis()->SetTitleSize(0.06);
   Graph_Graph5->GetYaxis()->SetTitleOffset(1.25);
   Graph_Graph5->GetYaxis()->SetTitleFont(42);
   Graph_Graph5->GetZaxis()->SetLabelFont(42);
   Graph_Graph5->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph5->GetZaxis()->SetLabelSize(0.05);
   Graph_Graph5->GetZaxis()->SetTitleSize(0.06);
   Graph_Graph5->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph5);
   
   gre->Draw("p");
   
   gre = new TGraphErrors(1);
   gre->SetName("Graph5");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerStyle(28);
   gre->SetMarkerSize(1.7);
   gre->SetPoint(0,0.54,0.104);
   gre->SetPointError(0,0,0.021);
   
   TH1F *Graph_Graph6 = new TH1F("Graph_Graph6","Graph",100,0.44,1.64);
   Graph_Graph6->SetMinimum(0.0788);
   Graph_Graph6->SetMaximum(0.1292);
   Graph_Graph6->SetDirectory(0);
   Graph_Graph6->SetStats(0);
   Graph_Graph6->SetLineStyle(0);
   Graph_Graph6->SetMarkerStyle(20);
   Graph_Graph6->GetXaxis()->SetLabelFont(42);
   Graph_Graph6->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph6->GetXaxis()->SetLabelSize(0.05);
   Graph_Graph6->GetXaxis()->SetTitleSize(0.06);
   Graph_Graph6->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph6->GetXaxis()->SetTitleFont(42);
   Graph_Graph6->GetYaxis()->SetLabelFont(42);
   Graph_Graph6->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph6->GetYaxis()->SetLabelSize(0.05);
   Graph_Graph6->GetYaxis()->SetTitleSize(0.06);
   Graph_Graph6->GetYaxis()->SetTitleOffset(1.25);
   Graph_Graph6->GetYaxis()->SetTitleFont(42);
   Graph_Graph6->GetZaxis()->SetLabelFont(42);
   Graph_Graph6->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph6->GetZaxis()->SetLabelSize(0.05);
   Graph_Graph6->GetZaxis()->SetTitleSize(0.06);
   Graph_Graph6->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph6);
   
   gre->Draw("p");
   line = new TLine(0.18,0.071,0.22,0.071);

   ci = TColor::GetColor("#cc33ff");
   line->SetLineColor(ci);
   line->SetLineWidth(3);
   line->Draw();
   TArrow *arrow = new TArrow(0.2,0.071,0.2,0.03,0.015,"|>");
   arrow->SetFillColor(1);
   arrow->SetFillStyle(1001);

   ci = TColor::GetColor("#cc33ff");
   arrow->SetLineColor(ci);
   arrow->SetLineWidth(3);
   arrow->Draw();
   
   TLegend *leg = new TLegend(0.2,0.5,0.7,0.75,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.035);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("NULL","Bottomonia","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("Graph","p_{T}#in [0,30] GeV/c, |y| < 2.4","");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Graph","HIN-16-023","");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Graph2","#varUpsilon(1S)","P");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#009900");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(29);
   entry->SetMarkerSize(1.7);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Graph3","#varUpsilon(2S)","P");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#000099");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(34);
   entry->SetMarkerSize(1.7);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Graph","#varUpsilon(3S) 95% C.L.","P");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#cc33ff");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(23);
   entry->SetMarkerSize(1.7);
   entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(1.03,0.45,"#varUpsilon(1S)");
   tex->SetTextFont(42);
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.52,0.17,"#varUpsilon(2S)");
   tex->SetTextFont(42);
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.22,0.12,"#varUpsilon(3S)");
   tex->SetTextFont(42);
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.99,1.1,"CMS");
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.08,1.1,"PbPb #sqrt{s_{NN}} = 5.02 TeV");
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.81,1.02,"Preliminary");
   tex->SetTextFont(52);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.08,1.02,"Cent. 0-100%");
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *phAxis__1 = new TH1F("phAxis__1","",1,0,1.2);
   phAxis__1->SetMinimum(0);
   phAxis__1->SetMaximum(1.2);
   phAxis__1->SetDirectory(0);
   phAxis__1->SetLineStyle(0);
   phAxis__1->SetMarkerStyle(20);
   phAxis__1->GetXaxis()->SetTitle("Binding energy [GeV]");
   phAxis__1->GetXaxis()->CenterTitle(true);
   phAxis__1->GetXaxis()->SetLabelFont(42);
   phAxis__1->GetXaxis()->SetLabelOffset(0.007);
   phAxis__1->GetXaxis()->SetLabelSize(0.05);
   phAxis__1->GetXaxis()->SetTitleSize(0.06);
   phAxis__1->GetXaxis()->SetTitleOffset(0.9);
   phAxis__1->GetXaxis()->SetTitleFont(42);
   phAxis__1->GetYaxis()->SetTitle("R_{AA}");
   phAxis__1->GetYaxis()->CenterTitle(true);
   phAxis__1->GetYaxis()->SetLabelFont(42);
   phAxis__1->GetYaxis()->SetLabelOffset(0.007);
   phAxis__1->GetYaxis()->SetLabelSize(0.05);
   phAxis__1->GetYaxis()->SetTitleSize(0.06);
   phAxis__1->GetYaxis()->SetTitleOffset(1.25);
   phAxis__1->GetYaxis()->SetTitleFont(42);
   phAxis__1->GetZaxis()->SetLabelFont(42);
   phAxis__1->GetZaxis()->SetLabelOffset(0.007);
   phAxis__1->GetZaxis()->SetLabelSize(0.05);
   phAxis__1->GetZaxis()->SetTitleSize(0.06);
   phAxis__1->GetZaxis()->SetTitleFont(42);
   phAxis__1->Draw("sameaxis");
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
